-- SQL para verificar estoque minimo e maximo e necessidade de compra
-- Vai filtrar por grupo de produto, produto e local de estoque e usuário que está responsável
SELECT 
    GRU.CODGRUPOPROD AS CODGRUPOPROD,
    GRU.DESCRGRUPOPROD AS DESCRICAO_GRUPO,
    PRO.CODPROD AS COD_PRODUTO,
    PRO.DESCRPROD AS DESCRICAO_PRODUTO,
    PRO.CODVOL AS UNIDADE,
    LOC.CODLOCAL AS COD_LEST, 
    LOC.DESCRLOCAL AS LOCAL_EST,
    PRO.ESTMIN  AS ESTQ_MIN,
    PRO.ESTMAX AS ESTQ_MAX,
    SUM(NVL(ROUND(EST.ESTOQUE, 2), 0)) AS ESTOQUE,
    NVL(PRO.ESTMAX,0) - SUM(NVL(EST.ESTOQUE,0)) AS NECESSIDADE_DE_COMPRA
FROM TGFGRU GRU
JOIN TGFPRO PRO
       ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
LEFT JOIN TGFEST EST
       ON PRO.CODPROD = EST.CODPROD 
      AND EST.CODLOCAL = PRO.CODLOCALPADRAO
LEFT JOIN TGFLOC LOC
       ON EST.CODLOCAL = LOC.CODLOCAL 
      AND LOC.CODLOCAL = PRO.CODLOCALPADRAO
WHERE 
    (PRO.ESTMAX - (NVL(EST.ESTOQUE,0) - NVL(EST.RESERVADO,0)) > 0)
    AND (GRU.CODGRUPOPROD = :P_CODGRUPOPROD OR :P_CODGRUPOPROD IS NULL)
    AND (PRO.CODPROD = :P_CODPROD OR :P_CODPROD IS NULL)
    AND ((LOC.CODLOCAL IN (SELECT CODLOCAL FROM TGFLOC WHERE AD_CODUSU = :P_USUARIO) AND :P_USUARIO IS NOT NULL) OR :P_USUARIO IS NULL )
GROUP BY 
    GRU.CODGRUPOPROD,
    GRU.DESCRGRUPOPROD,
    PRO.CODPROD,
    PRO.DESCRPROD,
    PRO.CODVOL,
    LOC.CODLOCAL, 
    LOC.DESCRLOCAL,
    PRO.ESTMIN,
    PRO.ESTMAX,
    NVL(PRO.ESTMAX,0)
HAVING SUM(NVL(EST.ESTOQUE,0)) <= PRO.ESTMIN
ORDER BY PRO.CODPROD