
--TABELA LOCAIS PARA VERIFICAR OS LOCAIS E NOVO CAMPO DE RESPONSAVEL ADICIONADO
SELECT * FROM TGFLOC


-------------------------------
--SELECT PARA MOSTRAR TODOS OS USUÁRIOS QUE ESTÃO VINCULADOS PARA OS LOCAIS DE ESTOQUE POR EXEMPLO
-- PARA UTILIZAR NO AGENDAMENTO DE ENVIO DO RELATORIO POR EXEMPLO
SELECT 
CODUSU AS P_USUARIO, 
USU.EMAIL, 
NULL AS P_CODPROD, 
NULL AS P_CODGRUPOPROD
FROM TGFLOC LOC
INNER JOIN TSIUSU USU ON (LOC.AD_CODUSU = USU.CODUSU) 